### ISSUE TITLE
What exact use cases does this dkv solve?

### ISSUE THREAD

**Issue by harishanumula** [flipkart-incubator/dkv#1]
Hey Guys, I was wondering about the specific situations for which this dkv is built. Aren't there already reliable distributed KV stores like etcd, TiKV, Consul.

**Comment by regunathb** [comment]
dkv has goals very similar to Facebook's ZippyDB : https://www.youtube.com/watch?v=ZRP7z0HnClc
We also want to make it capable of deployment across multiple data centres.
