### ISSUE TITLE
Allow Configuring DKV Server using an `app.conf` / `app.ini` file

### ISSUE THREAD

**Issue by kingster** [flipkart-incubator/dkv#93]
Today we have a lot of flags that we pass to the `dkvsrv`. Today even when configuring our server, we read these flags from a config file and then pass them as arguments. Instead, we can configure DKV to read the entire config params from the config file, with optional overrides via ENV/Arguments.

Possible Options

1.  [VIPER](https://github.com/spf13/viper)
2.  [HOCON](https://github.com/go-akka/configuration)

**Comment by rounakdatta** [comment]
Hi @kingster I'm willing to work on this issue.
- I've used viper before and was exploring viper/[koanf](https://github.com/knadh/koanf) for the purpose. Do you have a preference here?
- Given in this project we are already using .ini files for the other components (rocksdb, badger), we'd want to go ahead with the .ini config format itself right?

**Comment by kingster** [comment]
Hi rounak

Thank you for your interest in contributing to dkv.

> I've used viper before and was exploring viper/koanf for the purpose. Do you have a preference here?

IMO we should be good with either as long as it is compatible with standard flags, and allows us to selectivity override certain params. Also we use https://github.com/flipkart-incubator/nexus as one of the dependency which also expects certain flags, so we should be able to read our config file and programmatically set the value for those flags. 

> Given in this project we are already using .ini files for the other components (rocksdb, badger), we'd want to go ahead with the .ini config format itself right?

Yes, we can go ahead with ini format.
